sudo: false
language: csharp
solution: DepotDownloader.sln

install:
    - nuget restore DepotDownloader.sln

script:
    - xbuild /p:NoWarn=1584 DepotDownloader.sln /target:DepotDownloader

notifications:
    irc:
        channels:
            - "irc.gamesurge.net#opensteamworks"
        on_success: never
        on_failure: always

cache:
    directories:
        - "~/.local/share/NuGet/Cache"